name: dart_scripthash_generator
description: Will create an electrum scripthash from an address and network.
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {coinslib: ^3.1.3, crypto: ^3.0.2}
